### ISSUE TITLE
Introduce `decode_all` method that ensure that Input of decode is empty at end of call

### ISSUE THREAD

**Issue by thiolliere** [paritytech/parity-scale-codec#107]
I would expect that in some places people don't check that there input is actually empty after decoding a structure. And that is ok in some places but might not be in some other.

For example: in srml/contract:

https://github.com/paritytech/substrate/blob/1c2eaa3bc6a5659fb70cfcc88037573921612064/srml/contracts/src/wasm/runtime.rs#L566-L583

```rust
	ext_dispatch_call(ctx, call_ptr: u32, call_len: u32) => {
		let call = {
			let call_buf = read_sandbox_memory(ctx, call_ptr, call_len)?;
			<<<E as Ext>::T as Trait>::Call>::decode(&mut &call_buf[..])
				.ok_or_else(|| sandbox::HostError)?
		};

		// Charge gas for dispatching this call.
		let fee = {
			let balance_fee = <<E as Ext>::T as Trait>::ComputeDispatchFee::compute_dispatch_fee(&call);
			approx_gas_for_balance::<<E as Ext>::T>(ctx.gas_meter.gas_price(), balance_fee)
		};
```

this is ok but I wouldn't expect reading the code that `call_len` can be different from `call.encode().len()`

how about introducing a decode_all method that check that just check that input is empty after having decoded value. this cost nothing just adding a provided method on the trait Decode

**Comment by bkchr** [comment]
I'm not really sure this fits into the context of this codec, but as we otherwise would start to replicate the stuff all over the place, let's integrate it.
```
trait DecodeAll {
    fn decode_all(bla..);
}

impl DecodeAll for Decode {
    ...
}
```

I would like to see this as a different trait at least.
