### ISSUE TITLE
Improve preallocation by changing Input definition

### ISSUE THREAD

**Issue by thiolliere** [paritytech/parity-scale-codec#109]
fixed on v4 at https://github.com/paritytech/parity-scale-codec/pull/114
fixed on v3 at https://github.com/paritytech/parity-scale-codec/pull/108

but we want to improve the fix by changing input definition see Basti comment https://github.com/paritytech/parity-scale-codec/issues/109#issuecomment-505583916

**Comment by thiolliere** [comment]
for this to be implemented properly we need to get the size of the input, then we can allocate size of buffer according to input size, thus it would allow us to have the performance of allocating huge buffer and still not allow user to allocate huge buffer by crafting small inputs

**Comment by bkchr** [comment]
We would not allocate the buffer based on the input size. We need to introduce something like `minimum_size()` that returns the minimal size a data type requires in encoded format. Then we can check that `requested_len * minimum_size() <= input_len`. If this is true, we can continue. Maybe this needs a little bit more thinking, but should go into the right direction.

**Comment by thiolliere** [comment]
OK I made a bit of research:

I implemented the following additional associated function for the trait Input:
```rust
/// Trait that allows reading of data into a slice.
pub trait Input {
	/// Require the input to be at least the len specified.
	fn require_minimum_len(&mut self, len: usize) -> Result<(), Error>;

	/// Read the exact number of bytes required to fill the given buffer.
	///
	/// Note that this function is similar to `std::io::Read::read_exact` and not
	/// `std::io::Read::read`.
	fn read(&mut self, into: &mut [u8]) -> Result<(), Error>;

	/// Read a single byte from the input.
	fn read_byte(&mut self) -> Result<u8, Error> {
		let mut buf = [0u8];
		self.read(&mut buf[..])?;
		Ok(buf[0])
	}
}
```

thus ppl can implement this for a std::io::Read like this:
```rust
#[cfg(feature = "std")]
pub struct IoReader<R: std::io::Read> {
	buffer: Vec<u8>,
	reader: R,
}

#[cfg(feature = "std")]
impl<R: std::io::Read> Input for IoReader<R> {
	fn require_minimum_len(&mut self, len: usize) -> Result<(), Error> {
		if self.buffer.len() >= len {
			return Ok(())
		}

		let filled_len = self.buffer.len();
		self.buffer.resize(len, 0);
		self.reader.read_exact(&mut self.buffer[filled_len..])?;
		Ok(())
	}

	fn read(&mut self, into: &mut [u8]) -> Result<(), Error> {
		let into_len = into.len();
		let buffer_len = self.buffer.len();
		into.copy_from_slice(&self.buffer[..into_len.min(buffer_len)]);
		self.buffer.resize(buffer_len - into_len.min(buffer_len), 0);

		if into_len > buffer_len {
			self.reader.read_exact(&mut into[buffer_len..])?;
		}

		Ok(())
	}
}
```

then for `Vec<T>` I would do that:
```rust
impl<T: Decode> Decode for Vec<T> {
	fn decode<I: Input>(input: &mut I) -> Result<Self, Error> {
		<Compact<u32>>::decode(input).and_then(move |Compact(len)| {
			let len = len as usize;
			if let IsU8::Yes = <T as Decode>::IS_U8 {
				input.require_minimum_len(len)?;
				let mut r = vec![0; len];

				input.read(&mut r[..len])?;
				let r = unsafe { std::mem::transmute::<Vec<u8>, Vec<T>>(r) };
				Ok(r)
			} else {
				input.require_minimum_len(len*T::minimum_encoded_len())?; // Here maybe issue, see the comment below
				let mut r = Vec::with_capacity(len);
				for _ in 0..len {
					r.push(T::decode(input)?);
				}
				Ok(r)
			}
		})
	}
}
```
so here in order not to allocate too much capacity in Vec I implement a new function on Decode which is `minimum_encoded_len`
But this can be an issue if `T::minimum_encoded_len()` is very less than `size_of::<T>()` and if having lots of element with minimum_encoded_len is considered invalid.
Because someone can send a crafted input with only element with minimum_encoded_len and if will be a valid struct but unexpected.

Hmm I think it is fine, if the struct is valid then the job of parity-scale-codec is done, if creating a valid struct can make a lot of allocation it is just because the struct Encode/Decode has been badly derived/implemented.

**Comment by bkchr** [comment]
Yeah that sounds like a good direction and I had something similar in my mind.
