### ISSUE TITLE
Rethink input impl for `std::io::Read`

### ISSUE THREAD

**Issue by bkchr** [paritytech/parity-scale-codec#113]
I believe that's wrong. `std::io::Read::read` can just read less bytes in case they are not available yet (like when you read directly from network or a slow disk) - we should try in a loop until we get `0` like we do with dynamic allocation. I'd unify the two codes and just have a bool flag to control if we are allowed to go over current capacity.

_Originally posted by @tomusdrw in https://github.com/paritytech/parity-scale-codec/pull/108_

**Comment by bkchr** [comment]
We use https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact for the `std::io::Read` impl. So, we are safe and don't need to do that.

**Comment by tomusdrw** [comment]
We have actually changed that in #108 I think it still might be valid: https://github.com/paritytech/parity-scale-codec/blob/parity-codec-v3/src/codec.rs#L64

**Comment by bkchr** [comment]
Yeah :( Have seen this after @thiolliere commented on the pr. We fix this in the 4.0 branch.
