### ISSUE TITLE
Is there a reason for unit to drop input ?

### ISSUE THREAD

**Issue by thiolliere** [paritytech/parity-scale-codec#118]
the drop here: https://github.com/paritytech/parity-scale-codec/blob/master/derive/src/decode.rs#L31

is useless no ?

EDIT: there is the same for Encode of unit

**Comment by bkchr** [comment]
I'm not entirely sure, but it is probably to prevent `xy is unused` warnings in automatically derived code.
But from any other point, it is completely useless and does not do anything.
