### ISSUE TITLE
`min_encoded_len` doesn't work for recursive type

### ISSUE THREAD

**Issue by thiolliere** [paritytech/parity-scale-codec#131]
```rust
#[test]
fn stack_overflow() {
	#[derive(Encode, Decode)]
	pub enum Toto {
		T(Box<Toto>)
	}

	Toto::min_encoded_len();
}
```

**Comment by thiolliere** [comment]
one idea would be that min_encoded_len has one parameter which is a set of typeid and when implementing for a recursive type if its type id is already in the set then it returns max_value.

**Comment by thiolliere** [comment]
but this solution can be done in two way:
* every type register itself in the set (which is probably bad because it has some cost)
* potential recursive types register themself in the set (that means all abstract structure like Result, Box or some enums with only abstract variants).

Both solution seems bad actually

**Comment by thiolliere** [comment]
(at some point `const fn` could be of some help as it is not stable)

**Comment by thiolliere** [comment]
or we could do something like instead of having min_encoded_len returning the actual min_encoded_len it returns either a final result either a slice of callback, and those callbacks are discarded if there current computed result is more than the current minimum final result found.

But this seems overkill as well.

**Comment by thiolliere** [comment]
another solution would be to change the strategy completely.

At some point what do we want to handle as Input ? we usually use [u8] so we could easily bound preallocation with input len. The decoded value can need more allocation than input len due to skip, compact for example, but this limit should be good enough for most usage.

So the idea would be that intead of having decode requiring input to be a certain length we could do the other way around: having decoding asking a bound from input and input could return (maybe optionnaly) its len or whatever bound it thinks is fine.

**Comment by bkchr** [comment]
I think the last idea is the best.

**Comment by thiolliere** [comment]
though the third as for now the same flaws as the Fix currently in v4 as to say https://github.com/paritytech/parity-scale-codec/pull/108#issuecomment-505513896

> this fix is not perfect it allow to allocate in advance as such:
if you have Vec<Vec<Vec<_>>> then user can allocate MAX_PREALLOCATION_SIZE*3

to avoid this I can currently think of:
```rust
/// Trait that allows zero-copy read of value-references from slices in LE format.
pub trait Decode: Sized {
...
	/// Attempt to deserialise the value from input.
	fn decode<I: Input>(value: &mut I, input_used: usize) -> Result<Self, Error>;
}

/// Trait that allows reading of data into a slice.
pub trait Input {
...
	fn min_len(&mut self) -> usize {
		0
	}
}
```
`input_used`  is the len of the input used by caller so calle can't use this len to preallocate datas.

typically for `Vec<T>` if will call `input_reserve = (size_of::<T>()*vector_len).min(Input::min_len)` then it will call the decode of the first element with `input_used=input_reserve - size_of::<T>()` and then decode the second element with `input_used=input_reserve - 2*size_of::<T>()` etc...

By using this mecanism we have preallocation <= input_len.
Some allocation will be made like if Input::min_len is too small but those ones are standard vector growth ones.

**Comment by thiolliere** [comment]
actually it seems I found a solution to implement min_encoded_len using typeid in it seems an efficient way:

```rust
use std::any::TypeId;

pub trait Encode2: 'static {
	fn contains_for_sure_min_encoded_len_of<Typ: 'static>() -> bool;

	fn min_encoded_len() -> usize;
}

impl Encode2 for u32 {
	fn contains_for_sure_min_encoded_len_of<Typ: 'static>() -> bool {
		TypeId::of::<Typ>() == TypeId::of::<u32>()
	}
	fn min_encoded_len() -> usize { 4 }
}

pub enum SelfReference {
	A(Box<SelfReference>),
	B(u32),
}

impl Encode2 for SelfReference {
	fn contains_for_sure_min_encoded_len_of<Typ: 'static>() -> bool {
		false
	}

	fn min_encoded_len() -> usize {
		if Box::<SelfReference>::contains_for_sure_min_encoded_len_of::<Self>() {
			usize::max_value()
		} else {
			Box::<SelfReference>::min_encoded_len()
		}
		.min(
			if u32::contains_for_sure_min_encoded_len_of::<Self>() {
				usize::max_value()
			} else {
				u32::min_encoded_len()
			}
		)
		+ 1
	}
}

impl<T: Encode2> Encode2 for Box<T> {
	fn contains_for_sure_min_encoded_len_of<Typ: 'static>() -> bool {
		TypeId::of::<Typ>() == TypeId::of::<T>()
	}

	fn min_encoded_len() -> usize {
		T::min_encoded_len()
	}
}

fn main() {
	assert_eq!(SelfReference::min_encoded_len(), 5);
}
```

**Comment by thiolliere** [comment]
hmm it seems to work I want to research on it more but the example works
