### ISSUE TITLE
List other implementations of SCALE codec

### ISSUE THREAD

**Issue by kaichaosun** [paritytech/parity-scale-codec#133]
## Background
Users could use other languages to interact with Substrate blockchain, like Go, Python, etc. There are already existing implementations of SCALE. We can list these implementations to help people reuse it.

Another thought is: does a specification help improve people understand SCALE?

**Comment by bkchr** [comment]
We have a specification of scale encoding. The list of other language implementations should live in the near of the specification.
The specification should mention that there are the following implementations available: "...."

**Comment by kaichaosun** [comment]
The spec:
https://substrate.dev/docs/en/overview/low-level-data-format

**Comment by bkchr** [comment]
(the spec was also already linked in the readme)
