### ISSUE TITLE
Vecarray depends on parity-codec but it should be parity-scale-codec

### ISSUE THREAD

**Issue by thiolliere** [paritytech/parity-scale-codec#147]
so parity-scale-codec has a dependence to parity-codec through vecarray.

I think vecarray should be upgrade so that it uses parity-scale-codec.
Also is that possible to have parity-scale-codec depends on vecarray which depends on parity-scale-codec ?

**Comment by DarkEld3r** [comment]
As far as I can see, `vecarray` implements `Encode`/`Decode` (under feature), so it should be updated to use `parity-scale-codec` instead of `parity-codec` and implementation inside `parity-scale-codec` can be removed. Am I missing something?

**Comment by DarkEld3r** [comment]
It can be done the other way around: remove dependency and feature from `vecarray` and leave implementation inside `parity-scale-codec`.

**Comment by DarkEld3r** [comment]
I suppose it makes sense to leave the implementation inside `parity-scale-codec`: it has tests.
@sorpaas

**Comment by thiolliere** [comment]
actually it seem it is already fine now, vecarray impl encode for pairty-codec in a feature and it is implemented in parity-scale-codec, that works

**Comment by sorpaas** [comment]
I'm still having a few crates depending on `parity-codec`. That `parity-codec` flag on `vecarray` is exactly for that. Will definitely try to remove it at earliest possible time!

**Comment by thiolliere** [comment]
(Note that we could have released a new version of parity-codec as well)

**Comment by bkchr** [comment]
Hmm I'm not sure. Why not keep the implementation in vecarray? The whole rust ecosystem is doing it in the same way with serde. Serde just implements the std types, because it could not be done at the outside and any other crate depends on serde to provide the interfaces. While we can not convince the rest of the ecosystem to implement our traits, we at least can do this for parity related stuff.

**Comment by DarkEld3r** [comment]
I don't have a strong opinion here and my thought was exactly that: if we still need to put implementation for other types in `parity-scale-codec` itself, then we can put implementation for our types here too for "consistency". But your argument also makes sense.
