### ISSUE TITLE
Implement Serialize and Deserialize for all types implementing Encode and Decode

### ISSUE THREAD

**Issue by dvc94ch** [paritytech/parity-scale-codec#151]
We seem to have something like this in a couple of places in substrate. The `Deserialize` implementation is often missing. I think we could implement this for all types.

```rust
#[cfg(feature = "std")]
impl<Hash: Encode> ::serde::Serialize for DigestItem<Hash> {
	fn serialize<S>(&self, seq: S) -> Result<S::Ok, S::Error> where S: ::serde::Serializer {
		self.using_encoded(|bytes| {
			::primitives::bytes::serialize(bytes, seq)
		})
	}
}
```

**Comment by dvc94ch** [comment]
Actually I changed my mind, this is stupid

**Comment by smoelius** [comment]
@dvc94ch The title of this issue is exactly what I would like.

Could you please explain why you wrote the following?

> Actually I changed my mind, this is stupid

**Comment by dvc94ch** [comment]
Don't recall. But probably has something to do with it producing an unexpected result. If you serialize a struct it will produce a byte array. If you wanted Json you'll just end up with a big fat hex string

**Comment by smoelius** [comment]
OK. Thank you for your lightning-like reply. Cheers. :pray:
