### ISSUE TITLE
Bug for Decode

### ISSUE THREAD

**Issue by sman2013** [paritytech/parity-scale-codec#160]
Condition: `Vec<u8>` field (not only Vec<u8> type)

Giving a wrong bytes input, when decode the length of field, the length may be very large, then the `decode` method would alloc memory, panic!
The `decode` does't process wrong input.

Perhaps wo need some validation for input stream before alloc memory.

**Comment by bkchr** [comment]
Which version are you using? This is fixed in the latest versions.

**Comment by sman2013** [comment]
We used `version = "3.2"`.
So I think our project need to update this dependcy to the latest verison.

Thanks for your answer.
