### ISSUE TITLE
Derive macro should be documented and not hidden in the main crate reexport

### ISSUE THREAD

**Issue by thiolliere** [paritytech/parity-scale-codec#171]
The macro in parity-scale-codec-derive should be documented.
And the reexport in parity-scale-codec shouldn't reexport them with the attribute `hidden`
(EDIT: it shouldn't)

**Comment by bkchr** [comment]
Why should it be reexported as hidden?

**Comment by thiolliere** [comment]
it currently does reexport as hidden but it shouldn't, I misswrite
