### ISSUE TITLE
Add `skip()`

### ISSUE THREAD

**Issue by bkchr** [paritytech/parity-scale-codec#201]
The `Decode` trait should get a method `skip(input: &mut Input)` to skip an encoded object.

**Comment by thiolliere** [comment]
we do agree that skipping an encoded object shouldn't check that the object is valid.

So if someone works on untrusted data, skipping some part of the data to get the wanted part can succeed even if the data will actually fail to decode.

**Comment by bkchr** [comment]
We don't really check if an object is valid?

But yeah, normally we just skip the amount of expected bytes.

**Comment by thiolliere** [comment]
Maybe we should also introduce a new function:
```rust
/// Return the length of the type if fixed.
fn length() -> Option<usize> { None }
```

this would be used to optimized implementation of `Vec<T>::skip` and some other types
```rust
if let Some(size) = T::length {
  // decode compact and skip size*compact
}
```

**Comment by thiolliere** [comment]
skip is now part of Decode trait. I think we can close this issue in favor of https://github.com/paritytech/parity-scale-codec/issues/244
The idea is to release 2.0 soon so it can goes into next substrate release
