### ISSUE TITLE
How to read encoded values from TcpStream?

### ISSUE THREAD

**Issue by devashishdxt** [paritytech/parity-scale-codec#216]
I'm trying to read some SCALE encoded values from `TcpStream`. Is there a way to to this without initializing a big buffer?

**Comment by bkchr** [comment]
Did you tried [`IOReader`](https://github.com/paritytech/parity-scale-codec/blob/master/src/codec.rs#L194)?

**Comment by devashishdxt** [comment]
> Did you tried [`IOReader`](https://github.com/paritytech/parity-scale-codec/blob/master/src/codec.rs#L194)?

[`IoReader`](https://docs.rs/parity-scale-codec/1.3.4/parity_scale_codec/struct.IoReader.html#impl-Input) in latest released version requires `Seek` implementation which `TcpStream` does not implement.

**Comment by bkchr** [comment]
Just implement yourself a version that does not require seek?

**Comment by thiolliere** [comment]
actually the Seek usage is no longer used in the Input implementation, it is kept in order not to break semver.

You can do:
```
/// Wrapper that implements Input for any `Read` and `Seek` type.
///
/// NOTE: The remaining_len implementation returns `None` as Seek can return variable length.
#[cfg(feature = "std")]
pub struct IoReader<R: std::io::Read>(pub R);

#[cfg(feature = "std")]
impl<R: std::io::Read> Input for IoReader<R> {
	fn remaining_len(&mut self) -> Result<Option<usize>, Error> {
		Ok(None)
	}

	fn read(&mut self, into: &mut [u8]) -> Result<(), Error> {
		self.0.read_exact(into).map_err(Into::into)
	}
}
```
