### ISSUE TITLE
Compact integers encoding

### ISSUE THREAD

**Issue by kaichaosun** [paritytech/parity-scale-codec#230]
In the [docs](https://substrate.dev/docs/en/knowledgebase/advanced/codec#compactgeneral-integers), for mode `0b11`, there are 6 bits to encode the following bytes count for value.
The max bytes can be used: in binary `1111 11`, which is 63. 
The max value can be encoded in this mode should be `2^(63*8)-1`, which is `2^504-1`, but the doc says `2^536-1`.

Did I miss something, or the doc is wrong?

**Comment by xlc** [comment]
This is another doc I found somewhere in this repo (you may need to dig in the history to find the source.

```
// compact encoding:
// 0b00 00 00 00 / 00 00 00 00 / 00 00 00 00 / 00 00 00 00
//   xx xx xx 00                                                            (0 .. 2**6)     (u8)
//   yL yL yL 01 / yH yH yH yL                                              (2**6 .. 2**14) (u8, u16)  low LH high
//   zL zL zL 10 / zM zM zM zL / zM zM zM zM / zH zH zH zM                  (2**14 .. 2**30)    (u16, u32)  low LMMH high
//   nn nn nn 11 [ / zz zz zz zz ]{4 + n}                                   (2**30 .. 2**536)   (u32, u64, u128, U256, U512, U520) straight LE-encoded

// Note: we use *LOW BITS* of the LSB in LE encoding to encode the 2 bit key.

```

So you can see for `11` encoding, the byte size is `{4 + n}` and therefore the max value is `2^((63+4) * 8 - 1` which is `2^536-1`

There isn't need to use `11` encoding to represent 1-4 bytes because you should be using other encoding format.

**Comment by kaichaosun** [comment]
The doc do mentions this `The upper six bits are the number of bytes following, less four.`
And some code that explains [here](https://github.com/paritytech/parity-scale-codec/blob/9e966cb30c391fbdbc31796ec14d1c1aafa61034/src/compact.rs#L398).

Thanks @xlc
