### ISSUE TITLE
Better error type

### ISSUE THREAD

**Issue by bkchr** [paritytech/parity-scale-codec#238]
Currently we have an error type that mainly wraps around a static string. This makes it rather inflexible and the output often relative "bad". I propose to switch the error type to something more informative, especially one that can be used to give more context to a failure. Take the following code:

```
struct Test {
    test: DataType,
}

struct DataType {
     some_data: Vec<u32>,
}
```

Let's assume we would decode the `Test` from some invalid data. It would result in some error saying that the field `test` could not be decoded, but not giving some context. I think we should change the error to something like:

```
struct Error {
     cause: Option<Box<Error>>,
     desc: Cow<'static, str>,
}

impl Error {
     fn chain(self, desc: Cow) -> Self {
          Self { desc, cause: Box::new(self) }
     }
}
```

When printing this error we would get something like:
```
Could not decode `Error::test`:
     Could not decode `DataType::some_data` because there wasn't enough data to read the length.
```

Besides that we should hide the "chaining error" behind some feature. This brings the advance that someone could enable the "chaining error" on `no_std` as well to get better error output. If the chaining is disabled, we should just ignore the description or similar to let the compiler optimize it away.

All the examples/naming above are just for conveying the idea of what I would like to have :D

**Comment by thiolliere** [comment]
you expect ppl to use it in no_std only for debugging ? on not on production isn't it ?
