### ISSUE TITLE
funty 1.2 breaks constant resolution

### ISSUE THREAD

**Issue by dvdplm** [paritytech/parity-scale-codec#249]
`parity-scale-codec` depends on `bitvec` which depends on `funty` [at version `"1"`](https://github.com/bitvecto-rs/bitvec/blob/develop/Cargo.toml#L59). In projects that pull in the latest version, 1.2, there is a problem, e.g.:

```
error[E0034]: multiple applicable items in scope
   --> /Users/aggron/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/order.rs:476:7
    |
476 |             R::BITS,
    |                ^^^^ multiple `BITS` found
    |
note: candidate #1 is defined in the trait `BitMemory`
   --> /Users/aggron/.cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-0.20.1/src/mem.rs:44:2
    |
44  |     const BITS: u8 = mem::size_of::<Self>() as u8 * 8;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2 is defined in the trait `IsNumber`
   --> /Users/aggron/.cargo/registry/src/github.com-1ecc6299db9ec823/funty-1.2.0/src/lib.rs:144:2
    |
144 |     const BITS: u32;
    |     ^^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #1
    |
476 |             BitMemory::BITS,
    |             ^^^^^^^^^^^^^^^
help: disambiguate the associated constant for candidate #2
    |
476 |             IsNumber::BITS,
    |             ^^^^^^^^^^^^^^
```

(See for instance [this build of `parity-common`](https://ci.appveyor.com/project/paritytech/parity-common/builds/37773927) for full error)

The issue can be reproduced easily by adding `funty = "1.2"` to `parity-scale-codec`'s Cargo.toml.

Upstream issue [here](https://github.com/myrrlyn/funty/issues/3).

**Comment by dvdplm** [comment]
Also see: https://github.com/paritytech/polkadot/issues/2434

**Comment by dvdplm** [comment]
…and https://github.com/paritytech/cargo-contract/issues/176

**Comment by bkchr** [comment]
This is no bug on our side.
