### ISSUE TITLE
Support compact encoding for tuple enum items

### ISSUE THREAD

**Issue by gavofyork** [paritytech/parity-scale-codec#262]
This builds:
```
pub enum Example {
  Item { #[codec(compact)] x: u32 },
}
```

Yet this doesn't:
```
pub enum Example {
  Item ( #[codec(compact)] u32 ),
}
```

**Comment by thiolliere** [comment]
It should work already https://github.com/paritytech/parity-scale-codec/blob/f0341dabb01aa9ff0548558abb6dcc5c31c669a1/tests/mod.rs#L100-L107

I tried the example you provided and it worked to me.

**Comment by thiolliere** [comment]
tests cover the case and tests that it is indeed compact. thus I think we can close it
