### ISSUE TITLE
arrayvec 0.7 and const generics

### ISSUE THREAD

**Issue by elpiel** [paritytech/parity-scale-codec#264]
Because of the latest update of `arrayvec to 0.7` in `partiy-scale-codec 2.1` we've started experiencing breaking builds because we rely on `ethereum-types

This specific version of `arrayvec` uses the MVP const generics which was introduced in Rust 1.51

I've also opened an issue in `arrayvec` to add a minimum supported rust version in the README of the repository as this is only mentioned in docs.rs. Hopefully future issues like this will be avoided https://github.com/bluss/arrayvec/issues/185

![Screenshot from 2021-04-08 11-40-17](https://user-images.githubusercontent.com/8925621/113996029-73f9d500-985f-11eb-8318-5938fe43ac4e.png)

**Comment by bkchr** [comment]
We are aware that this requires the latest stable compiler. Not sure what you want to tell us with this issue?

**Comment by elpiel** [comment]
I find it intimidating that a minor version update of a dependency of a dependency of a dependency broke our docker build because of the minimum required version of rust.
We don't depend on `parity-scale-codec` directly and yet, because of the requirement of https://docs.rs/impl-codec/0.5.0/impl_codec/ of `parity-scale-code: ^2.0.0` we 

I'm looking for a way to avoid such problems in the future.
Should such changes be even considered minor changes if they brake working code bases?

**Comment by bkchr** [comment]
You probably have done a `cargo update`?

**Comment by ordian** [comment]
bumping minimum rust version is considered "possibly-breaking" change
we're waiting for https://github.com/rust-lang/rust/issues/65262 as a proper solution to this
for now we only support the latest stable

**Comment by elpiel** [comment]
> You probably have done a `cargo update`?

Actually we install the binary in docker, the only problem was, that we weren't passing `--locked` which will use the `Cargo.lock` file when doing the installation.

> bumping minimum rust version is [considered](https://doc.rust-lang.org/cargo/reference/semver.html#env-new-rust) "possibly-breaking" change
> we're waiting for [rust-lang/rust#65262](https://github.com/rust-lang/rust/issues/65262) as a proper solution to this
> for now we only support the latest stable

Thank you for bringing this to my attention, I'll take it into account the next time.
