### ISSUE TITLE
Add `nullable` attr to type field in `metadata.json`

### ISSUE THREAD

**Issue by yjhmelody** [paritytech/parity-scale-codec#281]
In other languages and unsafe rust. A field could be T | null type. 
It's obvious that some languages does not support `Option` type. They need to use null to represent `None`.
And in scale spec:
> Options
One or zero values of a particular type. Encoded as:
0x00 if it is None ("empty" or "null").
0x01 followed by the encoded value if it is Some.

So the `metadata.json` will be more generic if all `def` kind support  `nullable` attr.

**Comment by bkchr** [comment]
I also don't get it. But what is `metadata.json` anyway? Isn't that something ink specific?

**Comment by yjhmelody** [comment]
What I mean is that `pointer of type T` have not been considerred in `metadata.json`.
Its encoded data maybe is same with `Option<T>` in other language.
Other langs maybe not support Option<T> to represents Option<T> encoded data layout while they use `pointer of type T`, e.g. C/AssemblyScript.
Maybe should I open the issue on polkadotjs/app ?

**Comment by yjhmelody** [comment]
> I also don't get it. But what is `metadata.json` anyway? Isn't that something ink specific?

Currently, other languages must be compatible with metadata.json on apps, but this is not easy, at least not as easy as rust

**Comment by bkchr** [comment]
Just because languages don't have support for native `Option`, this doesn't mean it can not be translated. 

This is entirely about the parser and also not SCALE.

Thus, I'm going to close this issue.

**Comment by yjhmelody** [comment]
@bkchr  It's not about parser, it's about display type correctly and pretty for other language.  We can use `Option<T>` in metadata layout to represent `pointer of T`, but the type display is bad!!!!

**Comment by yjhmelody** [comment]
Why the design of metadata is always not universal enough and never consider the characteristics of other languages?

**Comment by ascjones** [comment]
This issue would have been best in `scale-info`. That said, `Option` itself does not have it's own `def` variant, it is only defined in terms of a custom built-in variant type. There is nothing to stop providing such a custom 3rd party type definition for a nullable type if required, but I see no need to add it as a built-in.
