### ISSUE TITLE
Document `encode_bound`, `decode_bound` and `encode_bound` custom attributes

### ISSUE THREAD

**Issue by emostov** [paritytech/parity-scale-codec#292]
#279 Adds the `mel_bound` derive. AFAICT it is not mentioned in the top level docs. It would be nice if it was mentioned in the top level docs for easy discoverability. (Maybe in the `Derive attributes` section?)

cc @KiChjang

**Comment by KiChjang** [comment]
For clarity, it's this part of the documentation: https://docs.rs/parity-scale-codec/2.3.0/parity_scale_codec/#derive-attributes

**Comment by wischli** [comment]
Would be great to have some documentation. I am currently upgrading all pallets to be bound in storage size and stumbled upon this derive which seems to be necessary in some cases. Would love to understand how to use it properly. In the Substrate repo it is mostly used without input.
