### ISSUE TITLE
derive `Encode`/`Decode` for `String` with `no_std`

### ISSUE THREAD

**Issue by mversic** [paritytech/parity-scale-codec#307]
Why is `String` encoding/decoding not supported with `no_std`? If there is a strong reason for this, can you give me some guidance how to best work around this without having to maintain a fork of this crate

**Comment by mversic** [comment]
I can make an implementation of this feature, if you would merge it upstream

**Comment by bkchr** [comment]
This is mainly to discourage people to use `String` in the runtime. Why do you need a `String`?

**Comment by mversic** [comment]
why would you like to discourage people to use `String` in runtime, but not `Vec` for example?

**Comment by mversic** [comment]
Why would `String` be a problematic structure? Also, `String` to me seems like a very ubiquitous structure.

In my specific case, I'm writing smartcontracts in Rust and compiling them to Wasm. I use `no_std` because I need my smartcontracts to be of small size and also because wasm module can't access system resources. Since Wasm doesn't have types other than integers nor does it at the moment offer some other way of exchanging data between host and module I have to **serialize** data to wasm's linear memory, send over pointer offset and length of the allocation, and deserialize on the other side. 
I'm using `parity-scale-codec` for other serializations and had wanted to use it in this context as well.

**Comment by bkchr** [comment]
If you want to use `String` in `no_std`, you just need to enable the `full` feature.

**Comment by mversic** [comment]
ok, tnx

**Comment by mversic** [comment]
pardon me, but I have one more question. What is meant by this comment on the `full` feature: `# WARNING: DO _NOT_ USE THIS FEATURE IF YOU ARE WORKING ON CONSENSUS CODE!*`? Is this specific to your use-case? I see that `full` is implied by `std` and we've been using this codec for a lot of things with `std` support

**Comment by bkchr** [comment]
> This is mainly to discourage people to use `String` in the runtime. 

It is what I meant with this comment. When building blockchains and using `String`s in the runtime shows that you are probably doing something wrong. Like you trying to store user data or whatever. In these cases it is better to hash the data and only store the hash.

**Comment by mversic** [comment]
I see, thank you very much for clarification
