### ISSUE TITLE
MaxEncodedLen not implemente for Vec

### ISSUE THREAD

**Issue by rakanalh** [paritytech/parity-scale-codec#312]
Hello,

Assuming we have the following type:
```
#[derive(MaxEncodedLen)]
struct Foo {
}
```

IIRC, `Vec<Foo>` should also be easy to implement such that:
```
impl<T: MaxEncodedLen> MaxEncodedLen for Vec<T> {}
```

I looked around in the codebase and i can see that other traits are implemented on `Vec` but not `MaxEncodedLen`. Would this be something that you would consider adding?

Thanks

**Comment by bkchr** [comment]
That doesn't work, because `MaxEncodedLen` works with a "static" context. Aka it doesn't know the number of elements of a `Vec`. For that, you can use `BoundedVec` and it friends, these will give you a `Vec` like interface and implement `MaxEncodedLen`. You can find them in Substrate.
