### ISSUE TITLE
`decode_all` should consume the input

### ISSUE THREAD

**Issue by bkchr** [paritytech/parity-scale-codec#313]
`decode_all` should consume the `input` to be more consistent with the normal `Decode` interface. By consuming I mean `&mut &[u8]`, so that we advance the input as we decode it.

**Comment by tomaka** [comment]
What's the point of doing this? If `DecodeAll` works correctly, then the slice will always be empty at the end?

**Comment by wigy-opensource-developer** [comment]
Exactly. And also it is easier to teach the API by having the same pattern for the signature of `decode`, `decode_limit` and `decode_all`.

**Comment by tomaka** [comment]
Why not teach `decode_all` and `decode_all_with_limit`, and tell people to never use `decode` and `decode_with_limit` unless they know what they're doing?

If this is about teaching, `decode` should have been named `decode_partial` to avoid confusion.

**Comment by wigy-opensource-developer** [comment]
That is a valid idea, but came too late to affect the v3 release. Maybe @bkchr can add more arguments for the signature change on `decode_all*` functions.

**Comment by bkchr** [comment]
> What was the point of doing this? If `DecodeAll` works correctly, then the slice will always be empty at the end?

And if decoding fails you would not have consumed any input. I have seen code that had basically a infinite loop because it assumed that input was consumed. The compiler was also not complaining that the function doesn't require any mutable reference as input.
