### ISSUE TITLE
How do I map a field to a custom name or add a mapping alias?

### ISSUE THREAD

**Issue by czyczk** [paritytech/parity-scale-codec#319]
I wanna map a field to a custom name or add a mapping alias to the field. Is it possible to do something like this in SCALE as in serde?

```
#[serde(alias = "resourceID")]
resource_id: String,
```

Actually I don't know if the JSON name mapping is done by Polkadot JS API or here. Apologies if this is not the right place to bring up this question, but I guess it's not that customizable on the Javascript side since the scale encoding in Polkadot JS API is more like a transparent process.

**Comment by bkchr** [comment]
SCALE doesn't encode any field names or similar. It just encodes the data without any structure. Not like json where you also see the structure of the data in the encoded format.
