### ISSUE TITLE
Make CompactRef public

### ISSUE THREAD

**Issue by andrenth** [paritytech/parity-scale-codec#320]
Hello

Would you consider making `CompactRef` public? I'm working on a project that requires serializing a vector size prefix manually, and it would be nice to be able to call `CompactRef(&len).encode_to(&mut buf)` instead of copying the compact encoding logic from the library. It's a trivial change, but I can open a PR if you'd like.

```diff
diff --git a/src/lib.rs b/src/lib.rs
index aaa5ac7..f7bfec7 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -291,7 +291,7 @@ pub use self::codec::{
 };
 #[cfg(feature = "std")]
 pub use self::codec::IoReader;
-pub use self::compact::{Compact, HasCompact, CompactAs, CompactLen};
+pub use self::compact::{Compact, HasCompact, CompactAs, CompactLen, CompactRef};
 pub use self::joiner::Joiner;
 pub use self::keyedvec::KeyedVec;
 pub use self::decode_all::DecodeAll;
```

**Comment by bkchr** [comment]
Yeah sounds okay :)
