### ISSUE TITLE
Question: Is the description intentionally `'static`? 

### ISSUE THREAD

**Issue by appetrosyan** [paritytech/parity-scale-codec#369]
Hi! We're using `parity_scale_codec` and came across the following peculiarity: it is not possible to construct a `parity_scale_codec::Error` from finite-lifetime objects. That is, from my understanding it is possible to attach a `dyn Error`, but not possible to set the description from e.g. `String`, because of the signature: 
```rust
#[derive(PartialEq, Eq, Clone, Debug)]
pub struct Error {
	#[cfg(feature = "chain-error")]
	cause: Option<Box<Error>>,
	#[cfg(feature = "chain-error")]
	desc: Cow<'static, str>, // <---- this thing! 
}
```

So for example converting from the result of `format!` is made complicated. Something like 

```rust 
impl Into<parity_scale_codec::Error> for MyError {
    fn into(self) -> parity_scale_codec::Error {
         self.reason.as_str().into()
    }
} 
```
doesn't pass the borrow checker if `reason` is `String`. 

I wanted to know if this is a technical limitation that has to be imposed for reasons not obvious from the context (i.e. relaxing the requirement would break another contract somewhere), or that this never came up before, and the `'static` lifetime limitation is purely an implementation detail. 

If possible, I would like to slightly adjust the definition, so that non-static strings could be used to package the offending values.

**Comment by bkchr** [comment]
If you would use anything else besides `'static` you would need to add the lifetime to `Error` and that is not really wanted. Here the point is that if you have a static string as description, we can store it without needing any allocation. 

To support your use case we need to add a `From<String>`. Then it should work.
