### ISSUE TITLE
Build error after crate update

### ISSUE THREAD

**Issue by www222fff** [paritytech/parity-scale-codec#379]
warning: profile package spec compiler_builtins in profile release did not match any packages
   Compiling parity-scale-codec v3.2.0
   Compiling ink_env v3.3.1
   Compiling pink-extension-macro v0.1.5
error[E0433]: failed to resolve: use of undeclared crate or module std
  --> /home/dannyaw/.cargo/registry/src/github.com-1ecc6299db9ec823/parity-scale-codec-3.2.0/src/max_encoded_len.rs:21:5
   |
21 | use std::ops::RangeInclusive;
   |     ^^^ use of undeclared crate or module std

For more information about this error, try rustc --explain E0433.
error: could not compile parity-scale-codec due to previous error

**Comment by bkchr** [comment]
We released 3.2.1. That fixes the problem
