### ISSUE TITLE
Review README links that are outdated

### ISSUE THREAD

**Issue by rlaferla** [paritytech/parity-scale-codec#391]
In the README.md, there are bad/outdated links.

e.g.  This link does not take the user to correct page but rather a landing page.

CompactAs
The CompactAs trait is used for wrapping custom types/structs as compact types, which makes them even more space/memory efficient. The compact encoding is described [here](https://docs.substrate.io/v3/advanced/scale-codec/#compactgeneral-integers).

**Comment by ashWhiteHat** [comment]
Fix with https://github.com/paritytech/parity-scale-codec/pull/394
