### ISSUE TITLE
Modify/remove the `#[codec(index)]` attribute

### ISSUE THREAD

**Issue by KiChjang** [paritytech/parity-scale-codec#399]
With the release of Rust 1.66, [discriminants are now allowed on enum variants with fields](https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html#explicit-discriminants-on-enums-with-fields). This makes it easier to encode variants -- instead of relying on the custom `#[codec(index)]` attribute, we can now directly encode the enum discriminant instead.

**Comment by bkchr** [comment]
> Enums with integer representations can now use explicit discriminants, even when they have fields.

We also support custom index for other enums. We could also already have supported this syntax, as this is a macro. However, it should be kept explicit on what this index is about.
