### ISSUE TITLE
Please provide `proc-macro` for libraries that re-exporting this library

### ISSUE THREAD

**Issue by clearloop** [paritytech/parity-scale-codec#416]
https://github.com/paritytech/parity-scale-codec/blob/1ecacab0d839778fa12ba4162ff541b2a7fc0f5b/derive/src/utils.rs#L130

is buggy since https://github.com/bkchr/proc-macro-crate/issues/34, however we can solve it with 

```rust
use scale_info::scale::Encode;

#[derive(Encode)]
#[serde(crate = scale_info::scale)]
struct Foo;
```

but this addition line is a bit verbose and ugly indeed, so maybe we can provide a `proc-macro` inside this repo to do the re-exporting job otherwise each of the libraries want to re-export this library will be buggy with the `derive` feature in some ways, they re-exported and they didn't, most of the users will import `the-long-name-parity-scale-codec` again

```rust
//! scale_info/src/lib.rs
scale::re_export!(); // doing the wrapping job for derive macros inside `parity-scale-codec` with the public re-exported path in this library
```

**Comment by bkchr** [comment]
```
scale::re_export!(); 
```

Not sure how this should work.
