### ISSUE TITLE
Marker trait `ConstEncodedLen`

### ISSUE THREAD

**Issue by ggwpez** [paritytech/parity-scale-codec#427]
As companion for the `MaxEncodedLen` trait i propose a `ConstEncodedLen` marker that should be applied to all types with constant encoded length. Definition:
 - For all instances `I` of type `T` must `I.encoded_len()` be equal to `T::max_encoded_len()`.

Eg. this holds for all integer types, but not for compact types and enums.

**Why is this needed?**

To guarantee that in-place memory operations are possible for a type. For example in the MQ pallet we have the [ItemHeader](https://github.com/paritytech/substrate/blob/1bbde5d7c50e55458ff3925ed0ee911d035719d5/frame/message-queue/src/lib.rs#L222) type that assumes to be `ConstEncodedLen` without a way to express it. Now if someone puts `Compact<u32>` for the `Size` type to conserve memory, it will inevitably corrupt the storage when attempting to do an in-place storage operation.  

<del>PS: Maybe we can also extend the `MaxEncodedLen` trait with an optional generic? Like `MaxEncodedLen<Len=ConstLen>` or whatever.</del>

**Comment by ggwpez** [comment]
Ups, I moved it.

**Comment by bkchr** [comment]
I don't really get why you need it, but I can see the benefit of this trait. I mean it shouldn't "harm" that much by having it.
