### ISSUE TITLE
3.6.9 release doesn't work with Acala

### ISSUE THREAD

**Issue by xlc** [paritytech/parity-scale-codec#569]
I did a `cargo update` for Acala and tests cannot compile. https://github.com/AcalaNetwork/Acala/actions/runs/7688750688/job/20950340271

Revert parity-scale-codec back to 3.6.5 and CI is happy to there must be some compatibility issue

Eyeballing the diff I will say it is one of deps bump breaks it and likely https://github.com/paritytech/parity-scale-codec/pull/535

**Comment by bkchr** [comment]
`cargo update -p proc-macro-crate` will fix your issue.
