### ISSUE TITLE
v3.7.0 is a breaking version

### ISSUE THREAD

**Issue by FabijanC** [paritytech/parity-scale-codec#656]
Version 3.7.0 broke the semver contract. The required Rustc version has been incremented to 1.79, thus breaking backwards compatibility, which should have made the new release 4.0.0 instead of 3.7.0. Unfortuantely I learned this the hard way ([broken CI / release process](https://app.circleci.com/pipelines/github/0xSpaceShard/starknet-devnet-rs/2836/workflows/2f776503-d842-4d55-b1d4-7ccacb3afbb1/jobs/4602)).

But not sure what's going on here; on [crates.io](https://crates.io/crates/parity-scale-codec/versions) v3.7.0 is the latest version, while on [GitHub](https://github.com/paritytech/parity-scale-codec/releases) it's v3.6.12. Was 3.7.0 a deliberate release?

**Comment by bkchr** [comment]
https://github.com/rust-lang/api-guidelines/discussions/231 and there are other discussions. MSRV bumps alongside a minor bump are fine, aka not semver breaking.

**Comment by FabijanC** [comment]
Thanks for the link. Basically breaking people's CI is by some not considered a breaking change. And even though they do not consider it a breaking change, they advise MSRV bumps to be included in breaking releases.

Moreover, for us, parity-scale-codec is not a direct dependency, but one of hundreds of dependencies of a dependency. Which makes it hard to track such changes. We were able to fix our CI by specifying parity-scale-codec (and parity-scale-odec-derive) as our direct dependencies with a `=3.6.12` requirement.

Since it seems you are not going to yank 3.7.0 and replace it with 4.0.0, feel free to close this issue.

**Comment by bkchr** [comment]
But don't you use a `Cargo.lock`? This should fix the dependency, even while `cargo publish`. At least when I understand https://github.com/rust-lang/cargo/issues/11148 correctly.

**Comment by FabijanC** [comment]
`Cargo.lock` was ignored in our case. And it seems it will be so until Rust v1.84, which should include this change: https://github.com/rust-lang/cargo/pull/14815
