### ISSUE TITLE
Improve Documentation 

### ISSUE THREAD

**Issue by bkchr** [paritytech/parity-scale-codec#79]
We should improve the general documentation, like how to implement `Compact` for unit structs.

Just some examples and an expresive readme.

**Comment by JoshOrndorff** [comment]
For cross reference https://docs.substrate.dev/docs/low-level-data-formats I'd like to follow along on this one.

**Comment by gautamdhameja** [comment]
Here's a draft for the docs (which can be the readme of this repo) - https://hackmd.io/ASZ4Z4pLRqyVYWiI9j1scA?view
This is a work in progress.

**Comment by gautamdhameja** [comment]
PR https://github.com/paritytech/parity-scale-codec/pull/94 addresses this issue.
